### ISSUE TITLE
unknown field 'Aliases' in struct literal of type cli.StringFlag

### ISSUE THREAD

**Issue by nephaste** [YamiOdymel/chaturbate-dvr#2]
Hi

Tried to built it for differents Arch but getting error

`./main.go:289:5: unknown field 'Aliases' in struct literal of type cli.StringFlag
./main.go:295:5: unknown field 'Aliases' in struct literal of type cli.IntFlag
`
go version go1.16.4 linux/amd64

export APP=chaturbate-dvr

go get github.com/grafov/m3u8
go get github.com/parnurzeal/gorequest
go get github.com/teacat/pathx
go get github.com/urfave/cli

GOOS=linux GOARCH=arm64 go build -o ${APP}.arm64 
GOOS=linux GOARCH=arm GOARM=5 go build -o ${APP}.armv5 
GOOS=linux GOARCH=arm GOARM=7 go build -o ${APP}.armv7 
GOOS=linux GOARCH=amd64 go build -o ${APP}.x64 
GOOS=linux GOARCH=386 go build -o ${APP}.i386 
GOOS=linux GOARCH=arm64 go build -o ${APP}.arm64

thanks for your help on this issue

![image](https://user-images.githubusercontent.com/3392684/141077193-0bd6fd05-3996-4e1f-bb73-4a8daf959520.png)

**Comment by YamiOdymel** [comment]
You might have to use `go get github.com/urfave/cli/v2` instead of `go get github.com/urfave/cli`

Because the `urfave/cli` has different versions. The project is a bit old and `go.mod` was not famous at the moment, sorry.

**Comment by YamiOdymel** [comment]
Hi, I've updated the source code and the `go.mod`, re-clone the repository and you should be fine.

**Comment by nephaste** [comment]
thanks a lot.... all is working as expected now  :)
